---
driver_plugin: vagrant
platforms:
- name: ubuntu-d1
  driver_config:
    box: opscode-ubuntu-1204-sda3
    network:
      private_network: "ip: '10.30.0.10'"
  run_list:
  - recipe[apt]
  attributes:
    drbd:
      master: true
      peers:
      - hostname: "pair-ubuntu-d1.vagrantup.com"
        address: "10.30.0.10"
        port: 7789
      - hostname: "pair-ubuntu-d2.vagrantup.com"
        address: "10.30.0.11"
        port: 7789
- name: ubuntu-d2
  driver_config:
    box: opscode-ubuntu-1204-sda3
    network:
      private_network: "ip: '10.30.0.11'"
  run_list:
  - recipe[apt]
  attributes:
    drbd:
      peers:
      - hostname: "pair-ubuntu-d1.vagrantup.com"
        address: "10.30.0.10"
        port: 7789
      - hostname: "pair-ubuntu-d2.vagrantup.com"
        address: "10.30.0.11"
        port: 7789
- name: centos-d1
  driver_config:
    box: opscode-centos-63-sda3
    network:
      private_network: "ip: '10.30.0.20'"
  attributes:
    drbd:
      master: true
      peers:
      - hostname: "pair-centos-d1.vagrantup.com"
        address: "10.30.0.20"
        port: 7789
      - hostname: "pair-centos-d2.vagrantup.com"
        address: "10.30.0.21"
        port: 7789
- name: centos-d2
  driver_config:
    box: opscode-centos-63-sda3
    network:
      private_network: "ip: '10.30.0.21'"
  attributes:
    drbd:
      peers:
      - hostname: "pair-centos-d1.vagrantup.com"
        address: "10.30.0.20"
        port: 7789
      - hostname: "pair-centos-d2.vagrantup.com"
        address: "10.30.0.21"
        port: 7789
suites:
- name: pair
  run_list:
  - recipe[xfs]
  - recipe[drbd::pair]
  attributes:
    drbd:
      disk: "/dev/sda3"
      mount: "/nfs"
      fs_type: "xfs"
